/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicInitForgetPasswordRouteImport } from './routes/_public/init-forget-password'
import { Route as AuthNavbarRouteImport } from './routes/_auth/_navbar'
import { Route as PublicPasswordResetTokenRouteImport } from './routes/_public/password-reset/$token'
import { Route as AuthNavbarDashboardIndexRouteImport } from './routes/_auth/_navbar/dashboard/index'
import { Route as PublicAuthOauthSuccessOauthResponseRouteImport } from './routes/_public/auth/oauth/success-oauth-response'
import { Route as PublicAuthOauthErrorOauthResponseRouteImport } from './routes/_public/auth/oauth/error-oauth-response'
import { Route as AuthNavbarDashboardUserSettingsRouteImport } from './routes/_auth/_navbar/dashboard/user-settings'
import { Route as AuthNavbarDashboardSummariesRouteImport } from './routes/_auth/_navbar/dashboard/summaries'
import { Route as AuthNavbarDashboardOverviewRouteImport } from './routes/_auth/_navbar/dashboard/overview'
import { Route as AuthNavbarDashboardWorkspaceIndexRouteImport } from './routes/_auth/_navbar/dashboard/workspace/index'
import { Route as AuthNavbarDashboardBotsPageBotsRouteImport } from './routes/_auth/_navbar/dashboard/bots-page/bots'
import { Route as AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRouteImport } from './routes/_auth/_navbar/dashboard/workspace/certain-workspace/$workspaceId'
import { Route as AuthNavbarDashboardBotsPageServerPageServerIdRouteImport } from './routes/_auth/_navbar/dashboard/bots-page/server-page/$serverId'
import { Route as AuthNavbarDashboardBotsPagePlatformPagePlatformIdRouteImport } from './routes/_auth/_navbar/dashboard/bots-page/platform-page/$platformId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicInitForgetPasswordRoute =
  PublicInitForgetPasswordRouteImport.update({
    id: '/init-forget-password',
    path: '/init-forget-password',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthNavbarRoute = AuthNavbarRouteImport.update({
  id: '/_navbar',
  getParentRoute: () => AuthRoute,
} as any)
const PublicPasswordResetTokenRoute =
  PublicPasswordResetTokenRouteImport.update({
    id: '/password-reset/$token',
    path: '/password-reset/$token',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthNavbarDashboardIndexRoute =
  AuthNavbarDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthNavbarRoute,
  } as any)
const PublicAuthOauthSuccessOauthResponseRoute =
  PublicAuthOauthSuccessOauthResponseRouteImport.update({
    id: '/auth/oauth/success-oauth-response',
    path: '/auth/oauth/success-oauth-response',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthOauthErrorOauthResponseRoute =
  PublicAuthOauthErrorOauthResponseRouteImport.update({
    id: '/auth/oauth/error-oauth-response',
    path: '/auth/oauth/error-oauth-response',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthNavbarDashboardUserSettingsRoute =
  AuthNavbarDashboardUserSettingsRouteImport.update({
    id: '/dashboard/user-settings',
    path: '/dashboard/user-settings',
    getParentRoute: () => AuthNavbarRoute,
  } as any)
const AuthNavbarDashboardSummariesRoute =
  AuthNavbarDashboardSummariesRouteImport.update({
    id: '/dashboard/summaries',
    path: '/dashboard/summaries',
    getParentRoute: () => AuthNavbarRoute,
  } as any)
const AuthNavbarDashboardOverviewRoute =
  AuthNavbarDashboardOverviewRouteImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => AuthNavbarRoute,
  } as any)
const AuthNavbarDashboardWorkspaceIndexRoute =
  AuthNavbarDashboardWorkspaceIndexRouteImport.update({
    id: '/dashboard/workspace/',
    path: '/dashboard/workspace/',
    getParentRoute: () => AuthNavbarRoute,
  } as any)
const AuthNavbarDashboardBotsPageBotsRoute =
  AuthNavbarDashboardBotsPageBotsRouteImport.update({
    id: '/dashboard/bots-page/bots',
    path: '/dashboard/bots-page/bots',
    getParentRoute: () => AuthNavbarRoute,
  } as any)
const AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRoute =
  AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRouteImport.update({
    id: '/dashboard/workspace/certain-workspace/$workspaceId',
    path: '/dashboard/workspace/certain-workspace/$workspaceId',
    getParentRoute: () => AuthNavbarRoute,
  } as any)
const AuthNavbarDashboardBotsPageServerPageServerIdRoute =
  AuthNavbarDashboardBotsPageServerPageServerIdRouteImport.update({
    id: '/dashboard/bots-page/server-page/$serverId',
    path: '/dashboard/bots-page/server-page/$serverId',
    getParentRoute: () => AuthNavbarRoute,
  } as any)
const AuthNavbarDashboardBotsPagePlatformPagePlatformIdRoute =
  AuthNavbarDashboardBotsPagePlatformPagePlatformIdRouteImport.update({
    id: '/dashboard/bots-page/platform-page/$platformId',
    path: '/dashboard/bots-page/platform-page/$platformId',
    getParentRoute: () => AuthNavbarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/init-forget-password': typeof PublicInitForgetPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/password-reset/$token': typeof PublicPasswordResetTokenRoute
  '/dashboard/overview': typeof AuthNavbarDashboardOverviewRoute
  '/dashboard/summaries': typeof AuthNavbarDashboardSummariesRoute
  '/dashboard/user-settings': typeof AuthNavbarDashboardUserSettingsRoute
  '/auth/oauth/error-oauth-response': typeof PublicAuthOauthErrorOauthResponseRoute
  '/auth/oauth/success-oauth-response': typeof PublicAuthOauthSuccessOauthResponseRoute
  '/dashboard': typeof AuthNavbarDashboardIndexRoute
  '/dashboard/bots-page/bots': typeof AuthNavbarDashboardBotsPageBotsRoute
  '/dashboard/workspace': typeof AuthNavbarDashboardWorkspaceIndexRoute
  '/dashboard/bots-page/platform-page/$platformId': typeof AuthNavbarDashboardBotsPagePlatformPagePlatformIdRoute
  '/dashboard/bots-page/server-page/$serverId': typeof AuthNavbarDashboardBotsPageServerPageServerIdRoute
  '/dashboard/workspace/certain-workspace/$workspaceId': typeof AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/init-forget-password': typeof PublicInitForgetPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/password-reset/$token': typeof PublicPasswordResetTokenRoute
  '/dashboard/overview': typeof AuthNavbarDashboardOverviewRoute
  '/dashboard/summaries': typeof AuthNavbarDashboardSummariesRoute
  '/dashboard/user-settings': typeof AuthNavbarDashboardUserSettingsRoute
  '/auth/oauth/error-oauth-response': typeof PublicAuthOauthErrorOauthResponseRoute
  '/auth/oauth/success-oauth-response': typeof PublicAuthOauthSuccessOauthResponseRoute
  '/dashboard': typeof AuthNavbarDashboardIndexRoute
  '/dashboard/bots-page/bots': typeof AuthNavbarDashboardBotsPageBotsRoute
  '/dashboard/workspace': typeof AuthNavbarDashboardWorkspaceIndexRoute
  '/dashboard/bots-page/platform-page/$platformId': typeof AuthNavbarDashboardBotsPagePlatformPagePlatformIdRoute
  '/dashboard/bots-page/server-page/$serverId': typeof AuthNavbarDashboardBotsPageServerPageServerIdRoute
  '/dashboard/workspace/certain-workspace/$workspaceId': typeof AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/_navbar': typeof AuthNavbarRouteWithChildren
  '/_public/init-forget-password': typeof PublicInitForgetPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/password-reset/$token': typeof PublicPasswordResetTokenRoute
  '/_auth/_navbar/dashboard/overview': typeof AuthNavbarDashboardOverviewRoute
  '/_auth/_navbar/dashboard/summaries': typeof AuthNavbarDashboardSummariesRoute
  '/_auth/_navbar/dashboard/user-settings': typeof AuthNavbarDashboardUserSettingsRoute
  '/_public/auth/oauth/error-oauth-response': typeof PublicAuthOauthErrorOauthResponseRoute
  '/_public/auth/oauth/success-oauth-response': typeof PublicAuthOauthSuccessOauthResponseRoute
  '/_auth/_navbar/dashboard/': typeof AuthNavbarDashboardIndexRoute
  '/_auth/_navbar/dashboard/bots-page/bots': typeof AuthNavbarDashboardBotsPageBotsRoute
  '/_auth/_navbar/dashboard/workspace/': typeof AuthNavbarDashboardWorkspaceIndexRoute
  '/_auth/_navbar/dashboard/bots-page/platform-page/$platformId': typeof AuthNavbarDashboardBotsPagePlatformPagePlatformIdRoute
  '/_auth/_navbar/dashboard/bots-page/server-page/$serverId': typeof AuthNavbarDashboardBotsPageServerPageServerIdRoute
  '/_auth/_navbar/dashboard/workspace/certain-workspace/$workspaceId': typeof AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/init-forget-password'
    | '/login'
    | '/register'
    | '/password-reset/$token'
    | '/dashboard/overview'
    | '/dashboard/summaries'
    | '/dashboard/user-settings'
    | '/auth/oauth/error-oauth-response'
    | '/auth/oauth/success-oauth-response'
    | '/dashboard'
    | '/dashboard/bots-page/bots'
    | '/dashboard/workspace'
    | '/dashboard/bots-page/platform-page/$platformId'
    | '/dashboard/bots-page/server-page/$serverId'
    | '/dashboard/workspace/certain-workspace/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/init-forget-password'
    | '/login'
    | '/register'
    | '/password-reset/$token'
    | '/dashboard/overview'
    | '/dashboard/summaries'
    | '/dashboard/user-settings'
    | '/auth/oauth/error-oauth-response'
    | '/auth/oauth/success-oauth-response'
    | '/dashboard'
    | '/dashboard/bots-page/bots'
    | '/dashboard/workspace'
    | '/dashboard/bots-page/platform-page/$platformId'
    | '/dashboard/bots-page/server-page/$serverId'
    | '/dashboard/workspace/certain-workspace/$workspaceId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/_navbar'
    | '/_public/init-forget-password'
    | '/_public/login'
    | '/_public/register'
    | '/_public/password-reset/$token'
    | '/_auth/_navbar/dashboard/overview'
    | '/_auth/_navbar/dashboard/summaries'
    | '/_auth/_navbar/dashboard/user-settings'
    | '/_public/auth/oauth/error-oauth-response'
    | '/_public/auth/oauth/success-oauth-response'
    | '/_auth/_navbar/dashboard/'
    | '/_auth/_navbar/dashboard/bots-page/bots'
    | '/_auth/_navbar/dashboard/workspace/'
    | '/_auth/_navbar/dashboard/bots-page/platform-page/$platformId'
    | '/_auth/_navbar/dashboard/bots-page/server-page/$serverId'
    | '/_auth/_navbar/dashboard/workspace/certain-workspace/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/init-forget-password': {
      id: '/_public/init-forget-password'
      path: '/init-forget-password'
      fullPath: '/init-forget-password'
      preLoaderRoute: typeof PublicInitForgetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/_navbar': {
      id: '/_auth/_navbar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthNavbarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/password-reset/$token': {
      id: '/_public/password-reset/$token'
      path: '/password-reset/$token'
      fullPath: '/password-reset/$token'
      preLoaderRoute: typeof PublicPasswordResetTokenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/_navbar/dashboard/': {
      id: '/_auth/_navbar/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthNavbarDashboardIndexRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
    '/_public/auth/oauth/success-oauth-response': {
      id: '/_public/auth/oauth/success-oauth-response'
      path: '/auth/oauth/success-oauth-response'
      fullPath: '/auth/oauth/success-oauth-response'
      preLoaderRoute: typeof PublicAuthOauthSuccessOauthResponseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/oauth/error-oauth-response': {
      id: '/_public/auth/oauth/error-oauth-response'
      path: '/auth/oauth/error-oauth-response'
      fullPath: '/auth/oauth/error-oauth-response'
      preLoaderRoute: typeof PublicAuthOauthErrorOauthResponseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/_navbar/dashboard/user-settings': {
      id: '/_auth/_navbar/dashboard/user-settings'
      path: '/dashboard/user-settings'
      fullPath: '/dashboard/user-settings'
      preLoaderRoute: typeof AuthNavbarDashboardUserSettingsRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
    '/_auth/_navbar/dashboard/summaries': {
      id: '/_auth/_navbar/dashboard/summaries'
      path: '/dashboard/summaries'
      fullPath: '/dashboard/summaries'
      preLoaderRoute: typeof AuthNavbarDashboardSummariesRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
    '/_auth/_navbar/dashboard/overview': {
      id: '/_auth/_navbar/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof AuthNavbarDashboardOverviewRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
    '/_auth/_navbar/dashboard/workspace/': {
      id: '/_auth/_navbar/dashboard/workspace/'
      path: '/dashboard/workspace'
      fullPath: '/dashboard/workspace'
      preLoaderRoute: typeof AuthNavbarDashboardWorkspaceIndexRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
    '/_auth/_navbar/dashboard/bots-page/bots': {
      id: '/_auth/_navbar/dashboard/bots-page/bots'
      path: '/dashboard/bots-page/bots'
      fullPath: '/dashboard/bots-page/bots'
      preLoaderRoute: typeof AuthNavbarDashboardBotsPageBotsRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
    '/_auth/_navbar/dashboard/workspace/certain-workspace/$workspaceId': {
      id: '/_auth/_navbar/dashboard/workspace/certain-workspace/$workspaceId'
      path: '/dashboard/workspace/certain-workspace/$workspaceId'
      fullPath: '/dashboard/workspace/certain-workspace/$workspaceId'
      preLoaderRoute: typeof AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
    '/_auth/_navbar/dashboard/bots-page/server-page/$serverId': {
      id: '/_auth/_navbar/dashboard/bots-page/server-page/$serverId'
      path: '/dashboard/bots-page/server-page/$serverId'
      fullPath: '/dashboard/bots-page/server-page/$serverId'
      preLoaderRoute: typeof AuthNavbarDashboardBotsPageServerPageServerIdRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
    '/_auth/_navbar/dashboard/bots-page/platform-page/$platformId': {
      id: '/_auth/_navbar/dashboard/bots-page/platform-page/$platformId'
      path: '/dashboard/bots-page/platform-page/$platformId'
      fullPath: '/dashboard/bots-page/platform-page/$platformId'
      preLoaderRoute: typeof AuthNavbarDashboardBotsPagePlatformPagePlatformIdRouteImport
      parentRoute: typeof AuthNavbarRoute
    }
  }
}

interface AuthNavbarRouteChildren {
  AuthNavbarDashboardOverviewRoute: typeof AuthNavbarDashboardOverviewRoute
  AuthNavbarDashboardSummariesRoute: typeof AuthNavbarDashboardSummariesRoute
  AuthNavbarDashboardUserSettingsRoute: typeof AuthNavbarDashboardUserSettingsRoute
  AuthNavbarDashboardIndexRoute: typeof AuthNavbarDashboardIndexRoute
  AuthNavbarDashboardBotsPageBotsRoute: typeof AuthNavbarDashboardBotsPageBotsRoute
  AuthNavbarDashboardWorkspaceIndexRoute: typeof AuthNavbarDashboardWorkspaceIndexRoute
  AuthNavbarDashboardBotsPagePlatformPagePlatformIdRoute: typeof AuthNavbarDashboardBotsPagePlatformPagePlatformIdRoute
  AuthNavbarDashboardBotsPageServerPageServerIdRoute: typeof AuthNavbarDashboardBotsPageServerPageServerIdRoute
  AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRoute: typeof AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRoute
}

const AuthNavbarRouteChildren: AuthNavbarRouteChildren = {
  AuthNavbarDashboardOverviewRoute: AuthNavbarDashboardOverviewRoute,
  AuthNavbarDashboardSummariesRoute: AuthNavbarDashboardSummariesRoute,
  AuthNavbarDashboardUserSettingsRoute: AuthNavbarDashboardUserSettingsRoute,
  AuthNavbarDashboardIndexRoute: AuthNavbarDashboardIndexRoute,
  AuthNavbarDashboardBotsPageBotsRoute: AuthNavbarDashboardBotsPageBotsRoute,
  AuthNavbarDashboardWorkspaceIndexRoute:
    AuthNavbarDashboardWorkspaceIndexRoute,
  AuthNavbarDashboardBotsPagePlatformPagePlatformIdRoute:
    AuthNavbarDashboardBotsPagePlatformPagePlatformIdRoute,
  AuthNavbarDashboardBotsPageServerPageServerIdRoute:
    AuthNavbarDashboardBotsPageServerPageServerIdRoute,
  AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRoute:
    AuthNavbarDashboardWorkspaceCertainWorkspaceWorkspaceIdRoute,
}

const AuthNavbarRouteWithChildren = AuthNavbarRoute._addFileChildren(
  AuthNavbarRouteChildren,
)

interface AuthRouteChildren {
  AuthNavbarRoute: typeof AuthNavbarRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNavbarRoute: AuthNavbarRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicInitForgetPasswordRoute: typeof PublicInitForgetPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicPasswordResetTokenRoute: typeof PublicPasswordResetTokenRoute
  PublicAuthOauthErrorOauthResponseRoute: typeof PublicAuthOauthErrorOauthResponseRoute
  PublicAuthOauthSuccessOauthResponseRoute: typeof PublicAuthOauthSuccessOauthResponseRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicInitForgetPasswordRoute: PublicInitForgetPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicPasswordResetTokenRoute: PublicPasswordResetTokenRoute,
  PublicAuthOauthErrorOauthResponseRoute:
    PublicAuthOauthErrorOauthResponseRoute,
  PublicAuthOauthSuccessOauthResponseRoute:
    PublicAuthOauthSuccessOauthResponseRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
